---
# WAN HUB Nodes

type: wan_rr

wan_rr: # dynamic_key: node_type
  defaults:
    # Set the maximum number of CPU used for the data plane.
    # This setting is useful on virtual Route Reflectors and Pathfinders where more CPU cores should be allocated for control plane.
    data_plane_cpu_allocation_max: 1 # Set to 1 for Lab, Set to 2 for AWE-7250R-16S
    loopback_ipv4_pool: 10.0.0.0/24
    vtep_loopback_ipv4_pool: 10.1.0.0/24
    filter:
      always_include_vrfs_in_tenants: [AUTOVPN-TENANT]
  nodes:
    - name: WEST-R1
      id: 1
      loopback_ipv4_address: 10.0.1.103
      mgmt_ip: 192.168.0.23/24
      vtep_loopback_ipv4_address: 10.1.1.103
      l3_interfaces:
        - name: Ethernet2
          profile: INTERNET-HUB-WAN-INTERFACE
          ip_address: 192.1.103.2/30
          wan_carrier: internet
          static_routes:
          - prefix: 192.0.0.0/13
          peer_ip: 192.1.103.1
    - name: EAST-R1
      id: 2
      loopback_ipv4_address: 10.0.2.103
      mgmt_ip: 192.168.0.33/24
      vtep_loopback_ipv4_address: 10.1.2.103
      l3_interfaces:
        - name: Ethernet2
          profile: INTERNET-HUB-WAN-INTERFACE
          ip_address: 192.2.103.2/30
          wan_carrier: internet
          static_routes:
          - prefix: 192.0.0.0/13
          peer_ip: 192.2.103.1

# DTLS for STUN is enabled by default
# It requires certificates to be generated and distributed on the participating
# devices. To disable it for a lab, uncomment the following line.
wan_stun_dtls_disable: true
