---

# EAST-R1 Router Configuration

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  vrf: A
  ip_address: 22.101.103.103/24
  shutdown: false
  switchport:
    enabled: false
