---

# Site 1 Router Configuration

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  flow_tracker:
    hardware: FLOW-TRACKER
- name: Ethernet2
  flow_tracker:
    hardware: FLOW-TRACKER

# # Disable Full Mesh (SPOKE-TO-SPOKE) to enforce HUB & SPOKE
# custom_structured_configuration_eos_cli: |-
#   router adaptive-virtual-topology
#     wan fabric
#       peer role edge
#         rule NoP2P region self zone self site exclude all
