---

# Site 3 Router Configuration

custom_structured_configuration_ethernet_interfaces:
- name: Ethernet1
  description: SW1
  switchport:
    enabled: false
- name: Ethernet1.70
  encapsulation_dot1q:
    vlan: 70
  vrf: A
  ip_address: 10.70.70.1/24
  shutdown: false

# Uncomment to Disable Full Mesh (SPOKE-TO-SPOKE) to enforce HUB & SPOKE
# custom_structured_configuration_eos_cli: |-
#   router adaptive-virtual-topology
#     wan fabric
#       peer role edge
#         rule NoP2P region self zone self site exclude all
