---

aaa_settings:
  # Local Users
  local_users:
    - name: admin
      privilege: 15
      role: network-admin
      sha512_password: "$6$dBV2TikvEhsviGQF$tXu/McA.AkuHvZk1/lCsegkR47ZCTJmAh/CgzdRvNn.Od9B3w69XdEW5cGWRUAmfr428P2HpfkEbNdkDucgaN/"
    - name: avd
      privilege: 15
      role: network-admin
      sha512_password: "$6$Th/KFTmIYnvxkb7Q$E3tHQxMVocrqis9cwTt.J3UpOx7DhgAuVtrIPXWIsHFhHP9QSZng13cNmcYwkTtUOVZuiyTqWt01W.t5fE9eR1"
    - name: cvpadmin
      privilege: 15
      role: network-admin
      sha512_password: "$6$dqXuoxAoGbFcWtzL$i7mEyybzlhsyY6jGKmV4NVGrOegDziitQLo4DYQLVG5EWpyVgxX.PeZLABz2XS/GJZE6kp7lURyA4Yi7/Bsjy0"
  # AAA Authorization Settings
  authorization:
    exec:
      default: local

mgmt_interface: Management1
mgmt_interface_vrf: default
default_mgmt_method: oob
# mgmt_gateway: 192.168.0.6

cv_settings:
  cvaas:
    enabled: true
    clusters:
      - name: cvaas
        region: staging
        token_file: "/tmp/cv-onboarding-token"
        vrf: default
  terminattr:
    disable_aaa: true
    ingestexclude: /Sysdb/cell/1/agent,/Sysdb/cell/2/agent

ntp_settings:
  server_vrf: default
  servers:
    - name: 0.us.pool.ntp.org

dns_settings:
  servers:
    - ip_address: 8.8.4.4
      vrf: default
    - ip_address: 8.8.8.8
      vrf: default

ipv4_acls:
  - name: ACL-HUB-INTERNET-IN
    entries:
      - sequence: 1
        remark: "Not for PRODUCTION: This ACL is built this way for the lab"
      - sequence: 10
        # IPSec traffic from anywhere
        action: permit
        protocol: udp
        source: any
        destination: interface_ip
        destination_ports_match: eq
        destination_ports: [isakmp, non500-isakmp]
      - sequence: 20
        # STUN traffic from anywhere
        action: permit
        protocol: udp
        source: any
        destination: interface_ip
        destination_ports_match: eq
        destination_ports: [3478]
      - sequence: 30
        # Troubleshooting
        action: permit
        protocol: icmp
        source: any
        destination: interface_ip
      - action: deny
        protocol: ip
        source: any
        destination: any
  - name: ACL-SPOKE-INTERNET-IN
    entries:
      - sequence: 1
        remark: "Not for PRODUCTION: This ACL is built this way for the lab"
      - sequence: 10
        # IPSec traffic from anywhere
        action: permit
        protocol: udp
        source: any
        destination: interface_ip
        destination_ports_match: eq
        destination_ports: [isakmp, non500-isakmp]
      - sequence: 30
        # Troubleshooting
        action: permit
        protocol: icmp
        source: any
        destination: interface_ip
      - action: deny
        protocol: ip
        source: any
        destination: any

skipped_tests:
  - category: AvdTestHardware
    tests:
      - VerifyEnvironmentPower
      - VerifyEnvironmentCooling
      - VerifyTemperature
      - VerifyTransceiversManufacturers

custom_structured_configuration_switchport_default:
  mode: "routed"

custom_structured_configuration_agents:
  - name: KernelFib
    environment_variables:
      - name: KERNELFIB_PROGRAM_ALL_ECMP
        value: "'true'"

custom_structured_configuration_management_ssh:
  client_alive:
    interval: 240
